//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace WebUI.Tiyi.Weixin.Work {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SendMsgServiceSoap", Namespace="http://www.zpitc.cn/")]
    public partial class SendMsgService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendTextToUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTextToTagsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendArticleToUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendArticleToTagsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertArticleToJsonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SendMsgService() {
            this.Url = global::WebUI.Properties.Settings.Default.WebUI_Tiyi_Weixin_Work_SendMsgService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendTextToUsersCompletedEventHandler SendTextToUsersCompleted;
        
        /// <remarks/>
        public event SendTextToTagsCompletedEventHandler SendTextToTagsCompleted;
        
        /// <remarks/>
        public event SendArticleToUserCompletedEventHandler SendArticleToUserCompleted;
        
        /// <remarks/>
        public event SendArticleToTagsCompletedEventHandler SendArticleToTagsCompleted;
        
        /// <remarks/>
        public event ConvertArticleToJsonCompletedEventHandler ConvertArticleToJsonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zpitc.cn/SendTextToUsers", RequestNamespace="http://www.zpitc.cn/", ResponseNamespace="http://www.zpitc.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendTextToUsers(string users, string text, string agentId) {
            object[] results = this.Invoke("SendTextToUsers", new object[] {
                        users,
                        text,
                        agentId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendTextToUsersAsync(string users, string text, string agentId) {
            this.SendTextToUsersAsync(users, text, agentId, null);
        }
        
        /// <remarks/>
        public void SendTextToUsersAsync(string users, string text, string agentId, object userState) {
            if ((this.SendTextToUsersOperationCompleted == null)) {
                this.SendTextToUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTextToUsersOperationCompleted);
            }
            this.InvokeAsync("SendTextToUsers", new object[] {
                        users,
                        text,
                        agentId}, this.SendTextToUsersOperationCompleted, userState);
        }
        
        private void OnSendTextToUsersOperationCompleted(object arg) {
            if ((this.SendTextToUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTextToUsersCompleted(this, new SendTextToUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zpitc.cn/SendTextToTags", RequestNamespace="http://www.zpitc.cn/", ResponseNamespace="http://www.zpitc.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendTextToTags(string tags, string text, string agentId) {
            object[] results = this.Invoke("SendTextToTags", new object[] {
                        tags,
                        text,
                        agentId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendTextToTagsAsync(string tags, string text, string agentId) {
            this.SendTextToTagsAsync(tags, text, agentId, null);
        }
        
        /// <remarks/>
        public void SendTextToTagsAsync(string tags, string text, string agentId, object userState) {
            if ((this.SendTextToTagsOperationCompleted == null)) {
                this.SendTextToTagsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTextToTagsOperationCompleted);
            }
            this.InvokeAsync("SendTextToTags", new object[] {
                        tags,
                        text,
                        agentId}, this.SendTextToTagsOperationCompleted, userState);
        }
        
        private void OnSendTextToTagsOperationCompleted(object arg) {
            if ((this.SendTextToTagsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTextToTagsCompleted(this, new SendTextToTagsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zpitc.cn/SendArticleToUser", RequestNamespace="http://www.zpitc.cn/", ResponseNamespace="http://www.zpitc.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendArticleToUser(string user, string articleJson, string agentId) {
            object[] results = this.Invoke("SendArticleToUser", new object[] {
                        user,
                        articleJson,
                        agentId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendArticleToUserAsync(string user, string articleJson, string agentId) {
            this.SendArticleToUserAsync(user, articleJson, agentId, null);
        }
        
        /// <remarks/>
        public void SendArticleToUserAsync(string user, string articleJson, string agentId, object userState) {
            if ((this.SendArticleToUserOperationCompleted == null)) {
                this.SendArticleToUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendArticleToUserOperationCompleted);
            }
            this.InvokeAsync("SendArticleToUser", new object[] {
                        user,
                        articleJson,
                        agentId}, this.SendArticleToUserOperationCompleted, userState);
        }
        
        private void OnSendArticleToUserOperationCompleted(object arg) {
            if ((this.SendArticleToUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendArticleToUserCompleted(this, new SendArticleToUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zpitc.cn/SendArticleToTags", RequestNamespace="http://www.zpitc.cn/", ResponseNamespace="http://www.zpitc.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendArticleToTags(string toTags, string articleJson, string agentId) {
            object[] results = this.Invoke("SendArticleToTags", new object[] {
                        toTags,
                        articleJson,
                        agentId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendArticleToTagsAsync(string toTags, string articleJson, string agentId) {
            this.SendArticleToTagsAsync(toTags, articleJson, agentId, null);
        }
        
        /// <remarks/>
        public void SendArticleToTagsAsync(string toTags, string articleJson, string agentId, object userState) {
            if ((this.SendArticleToTagsOperationCompleted == null)) {
                this.SendArticleToTagsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendArticleToTagsOperationCompleted);
            }
            this.InvokeAsync("SendArticleToTags", new object[] {
                        toTags,
                        articleJson,
                        agentId}, this.SendArticleToTagsOperationCompleted, userState);
        }
        
        private void OnSendArticleToTagsOperationCompleted(object arg) {
            if ((this.SendArticleToTagsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendArticleToTagsCompleted(this, new SendArticleToTagsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zpitc.cn/ConvertArticleToJson", RequestNamespace="http://www.zpitc.cn/", ResponseNamespace="http://www.zpitc.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConvertArticleToJson(Article article) {
            object[] results = this.Invoke("ConvertArticleToJson", new object[] {
                        article});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConvertArticleToJsonAsync(Article article) {
            this.ConvertArticleToJsonAsync(article, null);
        }
        
        /// <remarks/>
        public void ConvertArticleToJsonAsync(Article article, object userState) {
            if ((this.ConvertArticleToJsonOperationCompleted == null)) {
                this.ConvertArticleToJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertArticleToJsonOperationCompleted);
            }
            this.InvokeAsync("ConvertArticleToJson", new object[] {
                        article}, this.ConvertArticleToJsonOperationCompleted, userState);
        }
        
        private void OnConvertArticleToJsonOperationCompleted(object arg) {
            if ((this.ConvertArticleToJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertArticleToJsonCompleted(this, new ConvertArticleToJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zpitc.cn/")]
    public partial class Article {
        
        private string titleField;
        
        private string descriptionField;
        
        private string urlField;
        
        private string picUrlField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string PicUrl {
            get {
                return this.picUrlField;
            }
            set {
                this.picUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SendTextToUsersCompletedEventHandler(object sender, SendTextToUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTextToUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTextToUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SendTextToTagsCompletedEventHandler(object sender, SendTextToTagsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTextToTagsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTextToTagsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SendArticleToUserCompletedEventHandler(object sender, SendArticleToUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendArticleToUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendArticleToUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SendArticleToTagsCompletedEventHandler(object sender, SendArticleToTagsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendArticleToTagsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendArticleToTagsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ConvertArticleToJsonCompletedEventHandler(object sender, ConvertArticleToJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertArticleToJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertArticleToJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591