//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appliance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appliance()
        {
            this.Users = new HashSet<User>();
            this.BaoxiuBills = new HashSet<BaoxiuBill>();
        }
    
        public System.Guid AppId { get; set; }
        public string ProductSN { get; set; }
        public string AppName { get; set; }
        public string AppType { get; set; }
        public string Model { get; set; }
        public string PowerCold { get; set; }
        public string PowerHot { get; set; }
        public string Factory { get; set; }
        public Nullable<System.DateTime> ProductDate { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> ScrapDate { get; set; }
        public bool IsScrapped { get; set; }
        public bool IsUsing { get; set; }
        public string BigClass { get; set; }
        public string FixedSN { get; set; }
        public string AssetSN { get; set; }
        public string Power { get; set; }
        public string OwnerDepName { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoxiuBill> BaoxiuBills { get; set; }
    }
}
