//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoxiuBill
    {
        public System.Guid BxId { get; set; }
        public System.Guid AppId { get; set; }
        public string ProductSN { get; set; }
        public string BigClass { get; set; }
        public string AppType { get; set; }
        public string DepName { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public string UserMobilePhone { get; set; }
        public string FaultPhenomenon { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string HandleResult { get; set; }
        public bool IsAccept { get; set; }
        public bool IsCompleted { get; set; }
        public string UserMobileShort { get; set; }
        public bool IsCanceled { get; set; }
        public string Remark { get; set; }
    
        public virtual Appliance Appliance { get; set; }
    }
}
