//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporation
    {
        public System.Guid CorpId { get; set; }
        public string CorpName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> OrderIndex { get; set; }
        public string LinkmanName { get; set; }
        public string Telephone { get; set; }
        public string MobilePhone { get; set; }
        public string MobileShort { get; set; }
        public string Email { get; set; }
    }
}
