//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fault
    {
        public System.Guid FaultId { get; set; }
        public string FaultText { get; set; }
        public string BigClass { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
