//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JiadianDBEntities : DbContext
    {
        public JiadianDBEntities()
            : base("name=JiadianDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductSN> ProductSNs { get; set; }
        public virtual DbSet<Appliance> Appliances { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BaoxiuBill> BaoxiuBills { get; set; }
        public virtual DbSet<PaigongBill> PaigongBills { get; set; }
        public virtual DbSet<Repairman> Repairmen { get; set; }
    }
}
