//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSN
    {
        public System.Guid Id { get; set; }
        public int SN { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ActiveTime { get; set; }
        public Nullable<System.DateTime> Downtime { get; set; }
        public bool ActiveStatus { get; set; }
    }
}
