//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeibaoLog
    {
        public System.Guid WbId { get; set; }
        public Nullable<System.Guid> AppId { get; set; }
        public string FixedSN { get; set; }
        public string AssetSN { get; set; }
        public string ProductSN { get; set; }
        public string BigClass { get; set; }
        public string AppType { get; set; }
        public string OwerDepName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string WbContent { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> WbDate { get; set; }
        public string WbJobNumber { get; set; }
        public string WbRealName { get; set; }
    }
}
